import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import "./globals.css";
import { AppQueryClientProvider } from "@/lib/query-provider";

const inter = Catamaran({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppQueryClientProvider>{children}</AppQueryClientProvider>
      </body>
    </html>
  );
}
